//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkycAPI.EkycService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EkycService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOTPForAuth", ReplyAction="http://tempuri.org/IService1/GetOTPForAuthResponse")]
        System.Collections.Generic.Dictionary<string, string> GetOTPForAuth(string uidType, string strAadhaarNo, string strTransactionId, string ApplicationtxnId, string customerId, string TerminalId, string UserDetailId, string vendorId, string vendorPassword, string IPAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOTPForAuth", ReplyAction="http://tempuri.org/IService1/GetOTPForAuthResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetOTPForAuthAsync(string uidType, string strAadhaarNo, string strTransactionId, string ApplicationtxnId, string customerId, string TerminalId, string UserDetailId, string vendorId, string vendorPassword, string IPAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AuthenticationViaOTP", ReplyAction="http://tempuri.org/IService1/AuthenticationViaOTPResponse")]
        System.Collections.Generic.Dictionary<string, string> AuthenticationViaOTP(string uidType, string AadhaarNumber, string OTP, string TransactionsidOtp, string ApplicationtxnId, string customerId, string TerminalId, string UserDetailId, string vendorId, string vendorPassword, string IPAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AuthenticationViaOTP", ReplyAction="http://tempuri.org/IService1/AuthenticationViaOTPResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> AuthenticationViaOTPAsync(string uidType, string AadhaarNumber, string OTP, string TransactionsidOtp, string ApplicationtxnId, string customerId, string TerminalId, string UserDetailId, string vendorId, string vendorPassword, string IPAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DemographyAuthentication", ReplyAction="http://tempuri.org/IService1/DemographyAuthenticationResponse")]
        System.Collections.Generic.Dictionary<string, string> DemographyAuthentication(string uidType, string strAadhaarNumber, System.Collections.Generic.Dictionary<string, string> PidList, string PidOptions, string EkycType, string ApplicationtxnId, string customerId, string TerminalId, string UserDetailId, string vendorId, string vendorPassword, string IPAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DemographyAuthentication", ReplyAction="http://tempuri.org/IService1/DemographyAuthenticationResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> DemographyAuthenticationAsync(string uidType, string strAadhaarNumber, System.Collections.Generic.Dictionary<string, string> PidList, string PidOptions, string EkycType, string ApplicationtxnId, string customerId, string TerminalId, string UserDetailId, string vendorId, string vendorPassword, string IPAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AuthenticationViaBiometric", ReplyAction="http://tempuri.org/IService1/AuthenticationViaBiometricResponse")]
        System.Collections.Generic.Dictionary<string, string> AuthenticationViaBiometric(
                    string uidType, 
                    string strAadhaarNumber, 
                    string strEncryptedSKey, 
                    string encryptedPID, 
                    string sha256ofPidXML, 
                    string rdsId, 
                    string rdsVer, 
                    string mi, 
                    string mc, 
                    string dpId, 
                    string dc, 
                    string ci, 
                    string strTerminalId, 
                    string ts, 
                    string strTransactionId, 
                    string ApplicationtxnId, 
                    string BiometricType, 
                    string customerId, 
                    string UserDetailId, 
                    string vendorId, 
                    string vendorPassword, 
                    string IPAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AuthenticationViaBiometric", ReplyAction="http://tempuri.org/IService1/AuthenticationViaBiometricResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> AuthenticationViaBiometricAsync(
                    string uidType, 
                    string strAadhaarNumber, 
                    string strEncryptedSKey, 
                    string encryptedPID, 
                    string sha256ofPidXML, 
                    string rdsId, 
                    string rdsVer, 
                    string mi, 
                    string mc, 
                    string dpId, 
                    string dc, 
                    string ci, 
                    string strTerminalId, 
                    string ts, 
                    string strTransactionId, 
                    string ApplicationtxnId, 
                    string BiometricType, 
                    string customerId, 
                    string UserDetailId, 
                    string vendorId, 
                    string vendorPassword, 
                    string IPAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AuthenticationViaBFD", ReplyAction="http://tempuri.org/IService1/AuthenticationViaBFDResponse")]
        System.Collections.Generic.Dictionary<string, string> AuthenticationViaBFD(
                    string uidType, 
                    string AadhaarNumber, 
                    string strEncryptedSKey, 
                    string encryptedPID, 
                    string sha256ofPidXML, 
                    string rdsId, 
                    string rdsVer, 
                    string mi, 
                    string mc, 
                    string dpId, 
                    string dc, 
                    string ci, 
                    string TerminalId, 
                    string ts, 
                    string strTransactionId, 
                    string ApplicationtxnId, 
                    string BiometricType, 
                    string customerId, 
                    string UserDetailId, 
                    string vendorId, 
                    string vendorPassword, 
                    string IPAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AuthenticationViaBFD", ReplyAction="http://tempuri.org/IService1/AuthenticationViaBFDResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> AuthenticationViaBFDAsync(
                    string uidType, 
                    string AadhaarNumber, 
                    string strEncryptedSKey, 
                    string encryptedPID, 
                    string sha256ofPidXML, 
                    string rdsId, 
                    string rdsVer, 
                    string mi, 
                    string mc, 
                    string dpId, 
                    string dc, 
                    string ci, 
                    string TerminalId, 
                    string ts, 
                    string strTransactionId, 
                    string ApplicationtxnId, 
                    string BiometricType, 
                    string customerId, 
                    string UserDetailId, 
                    string vendorId, 
                    string vendorPassword, 
                    string IPAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOTP", ReplyAction="http://tempuri.org/IService1/GetOTPResponse")]
        System.Collections.Generic.Dictionary<string, string> GetOTP(string uidType, string strAadhaarNo, string strTransactionId, string ApplicationtxnId, string customerId, string TerminalId, string UserDetailId, string vendorId, string vendorPassword, string IPAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOTP", ReplyAction="http://tempuri.org/IService1/GetOTPResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetOTPAsync(string uidType, string strAadhaarNo, string strTransactionId, string ApplicationtxnId, string customerId, string TerminalId, string UserDetailId, string vendorId, string vendorPassword, string IPAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EkycViaOTP", ReplyAction="http://tempuri.org/IService1/EkycViaOTPResponse")]
        System.Collections.Generic.Dictionary<string, string> EkycViaOTP(string uidType, string strAadhaarNumber, string strOTP, string TransactionId, string ApplicationtxnId, string customerId, string TerminalId, string UserDetailId, string vendorId, string vendorPassword, string IPAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EkycViaOTP", ReplyAction="http://tempuri.org/IService1/EkycViaOTPResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> EkycViaOTPAsync(string uidType, string strAadhaarNumber, string strOTP, string TransactionId, string ApplicationtxnId, string customerId, string TerminalId, string UserDetailId, string vendorId, string vendorPassword, string IPAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EkycViaBiometric", ReplyAction="http://tempuri.org/IService1/EkycViaBiometricResponse")]
        System.Collections.Generic.Dictionary<string, string> EkycViaBiometric(
                    string uidType, 
                    string strAadhaarNumber, 
                    string strEncryptedSKey, 
                    string encryptedPID, 
                    string sha256ofPidXML, 
                    string rdsId, 
                    string rdsVer, 
                    string mi, 
                    string mc, 
                    string dpId, 
                    string dc, 
                    string ci, 
                    string strTerminalId, 
                    string ts, 
                    string strTransactionId, 
                    string ApplicationtxnId, 
                    string BiometricType, 
                    string customerId, 
                    string UserDetailId, 
                    string Consent, 
                    string vendorId, 
                    string vendorPassword, 
                    string IPAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EkycViaBiometric", ReplyAction="http://tempuri.org/IService1/EkycViaBiometricResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> EkycViaBiometricAsync(
                    string uidType, 
                    string strAadhaarNumber, 
                    string strEncryptedSKey, 
                    string encryptedPID, 
                    string sha256ofPidXML, 
                    string rdsId, 
                    string rdsVer, 
                    string mi, 
                    string mc, 
                    string dpId, 
                    string dc, 
                    string ci, 
                    string strTerminalId, 
                    string ts, 
                    string strTransactionId, 
                    string ApplicationtxnId, 
                    string BiometricType, 
                    string customerId, 
                    string UserDetailId, 
                    string Consent, 
                    string vendorId, 
                    string vendorPassword, 
                    string IPAddress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : EkycAPI.EkycService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<EkycAPI.EkycService.IService1>, EkycAPI.EkycService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetOTPForAuth(string uidType, string strAadhaarNo, string strTransactionId, string ApplicationtxnId, string customerId, string TerminalId, string UserDetailId, string vendorId, string vendorPassword, string IPAddress) {
            return base.Channel.GetOTPForAuth(uidType, strAadhaarNo, strTransactionId, ApplicationtxnId, customerId, TerminalId, UserDetailId, vendorId, vendorPassword, IPAddress);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetOTPForAuthAsync(string uidType, string strAadhaarNo, string strTransactionId, string ApplicationtxnId, string customerId, string TerminalId, string UserDetailId, string vendorId, string vendorPassword, string IPAddress) {
            return base.Channel.GetOTPForAuthAsync(uidType, strAadhaarNo, strTransactionId, ApplicationtxnId, customerId, TerminalId, UserDetailId, vendorId, vendorPassword, IPAddress);
        }
        
        public System.Collections.Generic.Dictionary<string, string> AuthenticationViaOTP(string uidType, string AadhaarNumber, string OTP, string TransactionsidOtp, string ApplicationtxnId, string customerId, string TerminalId, string UserDetailId, string vendorId, string vendorPassword, string IPAddress) {
            return base.Channel.AuthenticationViaOTP(uidType, AadhaarNumber, OTP, TransactionsidOtp, ApplicationtxnId, customerId, TerminalId, UserDetailId, vendorId, vendorPassword, IPAddress);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> AuthenticationViaOTPAsync(string uidType, string AadhaarNumber, string OTP, string TransactionsidOtp, string ApplicationtxnId, string customerId, string TerminalId, string UserDetailId, string vendorId, string vendorPassword, string IPAddress) {
            return base.Channel.AuthenticationViaOTPAsync(uidType, AadhaarNumber, OTP, TransactionsidOtp, ApplicationtxnId, customerId, TerminalId, UserDetailId, vendorId, vendorPassword, IPAddress);
        }
        
        public System.Collections.Generic.Dictionary<string, string> DemographyAuthentication(string uidType, string strAadhaarNumber, System.Collections.Generic.Dictionary<string, string> PidList, string PidOptions, string EkycType, string ApplicationtxnId, string customerId, string TerminalId, string UserDetailId, string vendorId, string vendorPassword, string IPAddress) {
            return base.Channel.DemographyAuthentication(uidType, strAadhaarNumber, PidList, PidOptions, EkycType, ApplicationtxnId, customerId, TerminalId, UserDetailId, vendorId, vendorPassword, IPAddress);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> DemographyAuthenticationAsync(string uidType, string strAadhaarNumber, System.Collections.Generic.Dictionary<string, string> PidList, string PidOptions, string EkycType, string ApplicationtxnId, string customerId, string TerminalId, string UserDetailId, string vendorId, string vendorPassword, string IPAddress) {
            return base.Channel.DemographyAuthenticationAsync(uidType, strAadhaarNumber, PidList, PidOptions, EkycType, ApplicationtxnId, customerId, TerminalId, UserDetailId, vendorId, vendorPassword, IPAddress);
        }
        
        public System.Collections.Generic.Dictionary<string, string> AuthenticationViaBiometric(
                    string uidType, 
                    string strAadhaarNumber, 
                    string strEncryptedSKey, 
                    string encryptedPID, 
                    string sha256ofPidXML, 
                    string rdsId, 
                    string rdsVer, 
                    string mi, 
                    string mc, 
                    string dpId, 
                    string dc, 
                    string ci, 
                    string strTerminalId, 
                    string ts, 
                    string strTransactionId, 
                    string ApplicationtxnId, 
                    string BiometricType, 
                    string customerId, 
                    string UserDetailId, 
                    string vendorId, 
                    string vendorPassword, 
                    string IPAddress) {
            return base.Channel.AuthenticationViaBiometric(uidType, strAadhaarNumber, strEncryptedSKey, encryptedPID, sha256ofPidXML, rdsId, rdsVer, mi, mc, dpId, dc, ci, strTerminalId, ts, strTransactionId, ApplicationtxnId, BiometricType, customerId, UserDetailId, vendorId, vendorPassword, IPAddress);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> AuthenticationViaBiometricAsync(
                    string uidType, 
                    string strAadhaarNumber, 
                    string strEncryptedSKey, 
                    string encryptedPID, 
                    string sha256ofPidXML, 
                    string rdsId, 
                    string rdsVer, 
                    string mi, 
                    string mc, 
                    string dpId, 
                    string dc, 
                    string ci, 
                    string strTerminalId, 
                    string ts, 
                    string strTransactionId, 
                    string ApplicationtxnId, 
                    string BiometricType, 
                    string customerId, 
                    string UserDetailId, 
                    string vendorId, 
                    string vendorPassword, 
                    string IPAddress) {
            return base.Channel.AuthenticationViaBiometricAsync(uidType, strAadhaarNumber, strEncryptedSKey, encryptedPID, sha256ofPidXML, rdsId, rdsVer, mi, mc, dpId, dc, ci, strTerminalId, ts, strTransactionId, ApplicationtxnId, BiometricType, customerId, UserDetailId, vendorId, vendorPassword, IPAddress);
        }
        
        public System.Collections.Generic.Dictionary<string, string> AuthenticationViaBFD(
                    string uidType, 
                    string AadhaarNumber, 
                    string strEncryptedSKey, 
                    string encryptedPID, 
                    string sha256ofPidXML, 
                    string rdsId, 
                    string rdsVer, 
                    string mi, 
                    string mc, 
                    string dpId, 
                    string dc, 
                    string ci, 
                    string TerminalId, 
                    string ts, 
                    string strTransactionId, 
                    string ApplicationtxnId, 
                    string BiometricType, 
                    string customerId, 
                    string UserDetailId, 
                    string vendorId, 
                    string vendorPassword, 
                    string IPAddress) {
            return base.Channel.AuthenticationViaBFD(uidType, AadhaarNumber, strEncryptedSKey, encryptedPID, sha256ofPidXML, rdsId, rdsVer, mi, mc, dpId, dc, ci, TerminalId, ts, strTransactionId, ApplicationtxnId, BiometricType, customerId, UserDetailId, vendorId, vendorPassword, IPAddress);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> AuthenticationViaBFDAsync(
                    string uidType, 
                    string AadhaarNumber, 
                    string strEncryptedSKey, 
                    string encryptedPID, 
                    string sha256ofPidXML, 
                    string rdsId, 
                    string rdsVer, 
                    string mi, 
                    string mc, 
                    string dpId, 
                    string dc, 
                    string ci, 
                    string TerminalId, 
                    string ts, 
                    string strTransactionId, 
                    string ApplicationtxnId, 
                    string BiometricType, 
                    string customerId, 
                    string UserDetailId, 
                    string vendorId, 
                    string vendorPassword, 
                    string IPAddress) {
            return base.Channel.AuthenticationViaBFDAsync(uidType, AadhaarNumber, strEncryptedSKey, encryptedPID, sha256ofPidXML, rdsId, rdsVer, mi, mc, dpId, dc, ci, TerminalId, ts, strTransactionId, ApplicationtxnId, BiometricType, customerId, UserDetailId, vendorId, vendorPassword, IPAddress);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetOTP(string uidType, string strAadhaarNo, string strTransactionId, string ApplicationtxnId, string customerId, string TerminalId, string UserDetailId, string vendorId, string vendorPassword, string IPAddress) {
            return base.Channel.GetOTP(uidType, strAadhaarNo, strTransactionId, ApplicationtxnId, customerId, TerminalId, UserDetailId, vendorId, vendorPassword, IPAddress);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetOTPAsync(string uidType, string strAadhaarNo, string strTransactionId, string ApplicationtxnId, string customerId, string TerminalId, string UserDetailId, string vendorId, string vendorPassword, string IPAddress) {
            return base.Channel.GetOTPAsync(uidType, strAadhaarNo, strTransactionId, ApplicationtxnId, customerId, TerminalId, UserDetailId, vendorId, vendorPassword, IPAddress);
        }
        
        public System.Collections.Generic.Dictionary<string, string> EkycViaOTP(string uidType, string strAadhaarNumber, string strOTP, string TransactionId, string ApplicationtxnId, string customerId, string TerminalId, string UserDetailId, string vendorId, string vendorPassword, string IPAddress) {
            return base.Channel.EkycViaOTP(uidType, strAadhaarNumber, strOTP, TransactionId, ApplicationtxnId, customerId, TerminalId, UserDetailId, vendorId, vendorPassword, IPAddress);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> EkycViaOTPAsync(string uidType, string strAadhaarNumber, string strOTP, string TransactionId, string ApplicationtxnId, string customerId, string TerminalId, string UserDetailId, string vendorId, string vendorPassword, string IPAddress) {
            return base.Channel.EkycViaOTPAsync(uidType, strAadhaarNumber, strOTP, TransactionId, ApplicationtxnId, customerId, TerminalId, UserDetailId, vendorId, vendorPassword, IPAddress);
        }
        
        public System.Collections.Generic.Dictionary<string, string> EkycViaBiometric(
                    string uidType, 
                    string strAadhaarNumber, 
                    string strEncryptedSKey, 
                    string encryptedPID, 
                    string sha256ofPidXML, 
                    string rdsId, 
                    string rdsVer, 
                    string mi, 
                    string mc, 
                    string dpId, 
                    string dc, 
                    string ci, 
                    string strTerminalId, 
                    string ts, 
                    string strTransactionId, 
                    string ApplicationtxnId, 
                    string BiometricType, 
                    string customerId, 
                    string UserDetailId, 
                    string Consent, 
                    string vendorId, 
                    string vendorPassword, 
                    string IPAddress) {
            return base.Channel.EkycViaBiometric(uidType, strAadhaarNumber, strEncryptedSKey, encryptedPID, sha256ofPidXML, rdsId, rdsVer, mi, mc, dpId, dc, ci, strTerminalId, ts, strTransactionId, ApplicationtxnId, BiometricType, customerId, UserDetailId, Consent, vendorId, vendorPassword, IPAddress);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> EkycViaBiometricAsync(
                    string uidType, 
                    string strAadhaarNumber, 
                    string strEncryptedSKey, 
                    string encryptedPID, 
                    string sha256ofPidXML, 
                    string rdsId, 
                    string rdsVer, 
                    string mi, 
                    string mc, 
                    string dpId, 
                    string dc, 
                    string ci, 
                    string strTerminalId, 
                    string ts, 
                    string strTransactionId, 
                    string ApplicationtxnId, 
                    string BiometricType, 
                    string customerId, 
                    string UserDetailId, 
                    string Consent, 
                    string vendorId, 
                    string vendorPassword, 
                    string IPAddress) {
            return base.Channel.EkycViaBiometricAsync(uidType, strAadhaarNumber, strEncryptedSKey, encryptedPID, sha256ofPidXML, rdsId, rdsVer, mi, mc, dpId, dc, ci, strTerminalId, ts, strTransactionId, ApplicationtxnId, BiometricType, customerId, UserDetailId, Consent, vendorId, vendorPassword, IPAddress);
        }
    }
}
